- name: Upload worker ignition file to the Swift
  os_object:
    cloud: "{{ openstack_cloud_name }}"
    state: present
    name: worker.ign
    container: "{{ openshift_cluster_id }}"
    filename: "{{ openshift_upi_directory }}/worker.ign"
    container_access: public


- name: Create compute node ports
  ignore_errors: True
  os_port:
    name: "{{ item.1 }}-{{ item.0 }}"
    network: "{{ os_network }}"
    security_groups:
      - "{{ os_worker_secgrp }}"
    allowed_address_pairs:
      - ip_address: "{{ subnet_range | next_nth_usable(7) }}"
    fixed_ips:
      - ip_address: "{{ subnet_range | next_nth_usable(openshift_workers_nth_usable_addr+item.0)}}"
  with_indexed_items: "{{ [os_port_worker] * compute_node_servers }}"

- name: Create compute node boot volumes
  os_volume:
    state: present
    size: "{{ openstack_boot_volume_size }}"
    display_name: "{{ item.1 }}-{{ item.0 }}-root"
    volume_type: "{{ openstack_boot_volume_type }}"
    image: "{{ rhcos_image_name }}"
    bootable: yes
  with_indexed_items: "{{ [os_worker_server_name] * compute_node_servers }}"

- name: Create compute node servers
  os_server:
    name: "{{ item.1 }}-{{ item.0 }}"
    boot_volume: "{{ item.1 }}-{{ item.0 }}-root"
    flavor: "{{ nodes_flavor }}"
    auto_ip: no
    userdata: "{{ lookup('file', openshift_upi_directory~'/worker.ign') | string }}"
    nics:
    - port-name: "{{ os_port_worker }}-{{ item.0 }}"
    meta:
      hostname: "{{ item.1 }}-{{ item.0 }}"
  with_indexed_items: "{{ [os_worker_server_name] * compute_node_servers }}"
