---
- name: Import initial setup checks
  import_tasks: initial_checks.yml
  check_mode: no

- name: Import openshift-installer playbook
  import_tasks: openshift_installer.yml

- name: Import rhcos image upload
  import_tasks: upload_rhcos_image.yml
  when: openstack_rhcos_image_name == "" 

- name: Import networking set facts playbook
  import_tasks: networking_set_facts.yml

- name: Remove cluster
  import_tasks: remove_cluster.yml
  when: REMOVE_OCP4_CLUSTER|bool

- name: Import security group playbook
  import_tasks: create_security_groups.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - skip_security_groups_creation is not defined

- name: Import network topology playbook
  import_tasks: create_network_topology.yml
  when: not REMOVE_OCP4_CLUSTER|bool

- name: Import fip's allocation playbook
  import_tasks: allocate_floating_ips.yml
  when: not REMOVE_OCP4_CLUSTER|bool

- name: Import bootstrap ignition playbook
  import_tasks: bootstrap_tasks.yml
  when: not REMOVE_OCP4_CLUSTER|bool

- name: Import bootstrap server playbook
  import_tasks: bootstrap_server.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - skip_bootstrap_server_creation is not defined

- name: "Wait for bootstrap server to prepare"
  pause:
    minutes: 4
  when: not REMOVE_OCP4_CLUSTER|bool

- name: Import control plane playbook
  import_tasks: control_plane_servers.yml
  when: 
    - not REMOVE_OCP4_CLUSTER|bool
    - skip_control_plane_servers_creation is not defined

- name: "Create API load balancer"
  import_tasks: create_api_loadbalancer.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - openshift_api_fip is defined
    - openshift_api_fip != ''

- name: "Wait for control server to finish installation"
  pause:
    minutes: 8
  when: not REMOVE_OCP4_CLUSTER|bool

- name: "Remove Bootstrap server"
  import_tasks: remove_bootstrap_server.yml
  when: not REMOVE_OCP4_CLUSTER|bool

- name: "Wait for master servers to take over Bootstrap server"
  pause:
    minutes: 1
  when: not REMOVE_OCP4_CLUSTER|bool

- name: "Create compute nodes"
  import_tasks: create_compute_nodes.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - skip_compute_nodes_creation is not defined

- name: "Create Ingress load balancer"
  import_tasks: create_ingress_loadbalancer.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - openshift_ingress_fip is defined
    - openshift_ingress_fip != ''

- name: "Create master servers second interface ports"
  import_tasks: create_master_servers_second_ports.yml
  when:
    - not REMOVE_OCP4_CLUSTER|bool
    - openshift_masters_second_network is defined
    - skip_masters_second_interface_creation is not defined
